version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: scorecard_db
      POSTGRES_USER: scorecard_user
      POSTGRES_PASSWORD: scorecard_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scorecard_user -d scorecard_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Credit Scorecard Microservice
  scorecard-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://scorecard_user:scorecard_pass@postgres:5432/scorecard_db
      - DEBUG=true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Redis (for future caching needs)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: